import { ResponseFormat } from "../../utils/response.format.js";

export const MEDICAL_INFORMATION_RESPONSE : Record<
'MEDICAL_INFORMATION_SAVED' | 
'MEDICAL_INFORMATION_NOT_SAVED' | 
'MEDICAL_INFORMATION_ALREADY_EXISTS' |
'MEDICAL_INFORMATION_NOT_FOUND' |
'MEDICAL_INFORMATION_UPDATED' |
'MEDICAL_INFORMATION_NOT_UPDATED' |
'MEDICAL_INFORMATION_DELETED' |
'MEDICAL_INFORMATION_NOT_DELETED'
, ResponseFormat> = {
  MEDICAL_INFORMATION_SAVED: new ResponseFormat(201, 'MEDICAL_INFORMATION SAVED'),
  MEDICAL_INFORMATION_NOT_SAVED: new ResponseFormat(400, 'MEDICAL_INFORMATION NOT SAVED'),
  MEDICAL_INFORMATION_ALREADY_EXISTS: new ResponseFormat(400, 'MEDICAL_INFORMATION ALREADY EXISTS'),
  MEDICAL_INFORMATION_NOT_FOUND: new ResponseFormat(404, 'MEDICAL_INFORMATION NOT FOUND'),
  MEDICAL_INFORMATION_UPDATED: new ResponseFormat(200, 'MEDICAL_INFORMATION UPDATED'),
  MEDICAL_INFORMATION_NOT_UPDATED: new ResponseFormat(400, 'MEDICAL_INFORMATION NOT UPDATED'),
  MEDICAL_INFORMATION_DELETED: new ResponseFormat(200, 'MEDICAL_INFORMATION DELETED'),
  MEDICAL_INFORMATION_NOT_DELETED: new ResponseFormat(400, 'MEDICAL_INFORMATION NOT DELETED'),
}