import { ResponseFormat } from "../../utils/response.format.js";

export const APPOINTMENT_RESPONSE : Record<
'APPOINTMENT_CREATED' | 
'APPOINTMENT_NOT_CREATED' | 
'APPOINTMENT_ALREADY_EXISTS' |
'APPOINTMENT_NOT_FOUND' |
'APPOINTMENT_UPDATED' |
'APPOINTMENT_NOT_UPDATED' |
'APPOINTMENT_DELETED' |
'APPOINTMENT_NOT_DELETED'
, ResponseFormat> = {
  APPOINTMENT_CREATED: new ResponseFormat(201, 'APPOINTMENT CREATED'),
  APPOINTMENT_NOT_CREATED: new ResponseFormat(400, 'APPOINTMENT NOT CREATED'),
  APPOINTMENT_ALREADY_EXISTS: new ResponseFormat(400, 'APPOINTMENT ALREADY EXISTS'),
  APPOINTMENT_NOT_FOUND: new ResponseFormat(404, 'APPOINTMENT NOT FOUND'),
  APPOINTMENT_UPDATED: new ResponseFormat(200, 'APPOINTMENT UPDATED'),
  APPOINTMENT_NOT_UPDATED: new ResponseFormat(400, 'APPOINTMENT NOT UPDATED'),
  APPOINTMENT_DELETED: new ResponseFormat(200, 'APPOINTMENT DELETED'),
  APPOINTMENT_NOT_DELETED: new ResponseFormat(400, 'APPOINTMENT NOT DELETED'),
}